POST http://localhost:5000/medications/add-medications
Content-Type: application/json

{
  "medications": [
    {
      "name": "Medication 1",
      "image_url": "https://example.com/medication1.jpg",
      "vendor_code": "12345"
    },
    {
      "name": "Medication 2",
      "image_url": "https://example.com/medication2.jpg",
      "vendor_code": "67890"
    }
  ]
}
